#ifndef _LANG_STR_H_
#define _LANG_STR_H_


//#define  USER_SECOND_BOOTLOADER
#define SUPPORT_LANG_CHINESE


typedef enum
{	
	LANG_ENGLISH,
	LANG_ZH_CN,
	LANG_SIZE,
} Lang_TypeDef;

typedef enum
{
	
	InitNetWorkStr,
    artnetTestStr,    
	FinalNetWorkStr,
	initDeviceStr,
	spaceStr,
	Menu0Line1Str,
	langLine1Str,
	langLine2Str,	
	saveSetupStr,
	backupStr,
	saveToStr,
	loadFromStr,
	usbAllSaveStr,
	usbLoadSingleStr,
	usbLoadAllStr,
	saveFailStr,
	loadFailStr,
	finishedStr,	
	sundayStr,
	mondayStr,
	tuesdayStr,
	wednesdayStr,
	thursdayStr,
	fridayStr,
	saturdayStr,
	timeCalendarStr,
	ydsStr,
	layoutSingleStr,
	layoutLeftRightStr,
	layoutUpDownStr,
	layout4cloumnStr,
	layout4rowStr,
	setTPmodeStr,
	scaleAndAdvanceStr,//scaleAndABmodeStr
	whiteStr,
	yellowStr,
	skyBlueStr,
	greenStr,
	pinkStr,
	redStr,
	blueStr,
	blackStr,

	// OUTPUT
	outputDetailStr,
	//outputStr,
	outputFormatStr,
	outputAdjustStr,
	scaleStr,
	scaleModeStr,
	autoFitStr,
	
	pressEscStr,
	companyInfoStr,

	baudrateStr,
	offStr,
	onStr,	
	tpModeStr,
	tpColorStr,
	tpRollStr,
	tpForeStr,
	tpBackStr,
	loopSourceStr,
	deOnOffStr,
	deHstartStr,
	deVstartStr,
	deWidthStr,
	deHeightStr,
	deAndHdmiStr,
	posXStr,
	posYStr,
	
	hdmiDviStr,
	hdmiSdiStr,
	sdiDviStr,
	sdiHdmiStr,
	dviHdmiStr,
	dviSdiStr,
	updateFile1Str,
	updateFile2Str,
	updateFirmwareStr, 
	usbUpdateFirmwareStr,
	pleaseWaitStr,
	updateFirmwareSuccessStr,
	updateFirmwareFailStr,
	pleaseRestartStr,
	pleaseTryAgainStr,
	inputSourceSelectStr,
	setToFreezeStr,
	setToLiveStr,
	brightnessStr,
	contrastStr,
	colorEffectStr,
	sharpnessStr,//20110906
	saturationStr,
	colorTempRedStr,
	colorTempGreenStr,
	colorTempBlueStr,
	colorTempStr,
	Color2800KStr,
	Color3200KStr,
	Color3500KStr,
	Color4000KStr,
	Color4500KStr,
	Color5000KStr,
	Color5600KStr,
	Color6000KStr,
	Color6500KStr,
	Color8000KStr,	
	fullRGBStr,
	
	volumeStr,
	pictureModeStr,

	updateMainBoardStr,
	pleaseEnterSelStr,
	screenPosXStr,
	screenPosYStr,
	screenWidthStr,
	screenHeightStr,
	//splitSetupStr,
	//splitModeAndPosStr,
	//splitModeStr,
	//splitPosX1Str,
	//splitPosX2Str,
	//splitPosY1Str,
	//splitPosY2Str,
	windowRatioStr,
	pictureStr,
	ratio_4_3_str,
	ratio_6_9_str,
	ratio_normal_str,
	
	noFileStr,
	tpOnOffStr,
	swapTopBottomStr,
	topBlackStr,
	imageStr,
	videoStr,
	dataRangeStr,
	deAdjustStr,

	resetStr,
	defaultStr,
	videoInputStr,
	inputStr,
	programStr,
	previewStr,
	programStr1,
	previewStr1,
	preStr,
	postStr,
	outputStr,
	formatStr,
	systemStr,
	systemInfoStr,
	advancedStr,
	dateTimeStr,
	ethernetStr,
	networkStr,
	lockPanelStr,
	lockPanelPasswordStr,
	licenseSetupStr,
	canUseTimeStr,
	noLimitStr,
	changePasswordStr,
	inputNewPasswordStr,
	inputPasswordAgainStr,
	twoPasswordsStr,
	doNotMatchStr,
	successStr,
	enterPasswordStr,	
	passwordStr,
	passwordErrorStr,
	retypePasswordStr,	
	licenseStateStr,
	changeTimeStr,
	changeDateStr,
	

	inputDetailStr,
	autoStr,
	hSizeStr,
	vSizeStr,
	HVSizeStr,
	hPosStr,
	vPosStr,
	positionSettStr,
	offsetSettingsStr,
	port12hOffsetStr,
	port12vOffsetStr,
	port34hOffsetStr,
	port34vOffsetStr,		
	vgaAdjustStr,
	SdiAdjustStr,
	clockStr,
	phaseStr,
	autoAdjustStr,
	screenStr,
	modeStr,
	FullSizeStr,
	ScreenSizeStr,
	portStr,
	deStr,
	dviStr,
	hdmiStr,
	sdiStr,	
	dviModeStr,
	deHPosStr,
	deVPosStr,
	deHSizeStr,
	deVSizeStr,
	
	
	gammaStr,
	transitionStr,
	fadeTypeStr,
	fadeTimeStr,
	alphaStr,
	fadeStr,
	cutStr,
	popCenterStr,
	pushCenterStr,
	popLTStr,
	pushLTStr,
	popRTStr,
	pushRTStr,
	popLBStr,
	pushLBStr,
	popRBStr,
	pushRBStr,
	popLeftStr,
	pushLeftStr,
	popRightStr,
	pushRightStr,
	popTopStr,
	pushTopStr,
	popBottomStr,
	pushBottomStr,
	
	noneStr,
	liveStr,
	freezeStr,
	flatStr,
	tpSwitchStr,
	testPatternStr,
	autoTpTimeStr,
	tpHorStepStr,
	tpVerStepStr,
	tpStepColorStr,
	
	pipStr,
	pipSourceStr,
	topWindowStr,
	swapWindowStr,
	layoutStr,
	selectStr,
	textOverlayStr,
	presetStr,
	blendModeStr,
	blendLevelStr,
	aboveBelowStr,
	andOrStr,

	userStr,
	//WhiteOnBlack1Str,
	//WhiteOnBlack2Str,
	//BlackOnWhite1Str,
	//BlackOnWhite2Str,
	//GreenOnBlack1Str,
	//GreenOnBlack2Str,
	//GreenOnWhite1Str,
	//GreenOnWhite2Str,
	//RedOnBlack1Str,
	//RedOnBlack2Str,
	//RedOnWhite1Str,
	//RedOnWhite2Str,
	
	// layout
	pipLTStr,
	pipRTStr,
	pipLBStr,
	pipRBStr,	
	pipCntStr,
	pbpLRStr,
	pbpTBStr,

	imageAStr,
	imageBStr,

	languageStr,
	englishStr,
	chineseStr,
	displayModeStr,
	flatColorStr,
	audioStr,
	muteStr,
	audioInStr,
	internalStr,
	externalStr,
	factoryResetStr,
	saveIpResetStr,
	noStr,
	yesStr,
	yesOrNoStr,

	// TechSupport  String
	techSupportStr,	
	salesHotlineStr,
	salesNumberStr,
	afterSaleHotlineStr,
	afterSaleNumberStr,
	phoneStr,
	emailStr,
	webSiteStr,
	
	ipStr,
	pressMenuKeyStr,//pressMenuSelKeyStr,
	toUnlockPanelStr,
	unLockPanelStr,
	adcAdjustStr,
	adcAutoAdjustStr,
	adcResetAllStr,
	invalidOperationStr,
	inPipModeStr,
	LockModeStr,
	lockSourceStr,
	freeRunStr,
	frameLock1Str,
	frameLock2Str,
	dateStr,
	timeStr,
	workTimeStr,
	totalWorkTimeStr,
	bootTimesStr,
	timingControlStr,
	hoursStr,
	minutesStr,
	delayCallSaveStr,
	
	belowStr,
	aboveStr,
	orStr,
	andStr,
	nullStr,

	syncStr,
	
	blackScreenStr,

	rgb444Str,
	yuv444Str,
	yuv422Str,
	colorSpaceStr,
	interlaceSwitchStr,
	
	//##########################################################################################
	//ART-NET
	setIpAddressStr,
	setRemoteIpAddress,	// setRemoteIpAddressStr,
	setLocalIpAddress,	// setLocalIpAddressStr,
	setSubnetMaskStr,
	setGatewayStr,
	dhcpEnableStr,
	vLockLineStr,

	splitStr,
	FourPortSplitStr,
	MIMOStr,
	independentModeStr,
	twoInThreeOutSrt,
	twoInFourOutSrt,
	threeInThreeOutSrt,
	threeInFourOutSrt,
	fourInFourOutSrt,

	// SPLIT
	//splitStr,
	hTotalSplitStr,
	vTotalSplitStr,
	hPosSplitStr,
	vPosSplitStr,
	hSizeSplitStr,
	vSizeSplitStr,

	//output format
	standardFormatStr,
	otherFormatStr,
	customFormatStr,

	//tips
	saveToPageTipsStr1,
	saveToPageTipsStr2,
	loadFromPageTipsStr1,
	loadFromPageTipsStr2,
	saveToRecoededWarnStr_beforeNum,
	saveToRecoededWarnStr_afterNum,
	guideSetNumberStr1,
	guideSetNumberStr2,
	guideSetNumbersToSourceStr,
	guideChooseItemStr1,
	guideChooseItemStr2,
	guideSaveStr1,
	guideSaveStr2,
	guideSaveToOneTipsStr,
	lockPanelTipsStr,
	beyondCustomFormatStr,
	imageEnhanceWarnStr1,
	imageEnhanceWarnStr2,
	imageEnhanceWarnStr3,	
	imageEnhanceEnableStr,

	//guide
	guideSetLanguageStr,
	guideEnglishStr,
	guideSetOutputFormatStr,
	guideSetScreenWidthStr,
	guideSetScreenHeightStr,
	guideSetScreenXPosStr,
	guideSetScreenYPosStr,
	guideSetSourceStr,
	guideSetSaveStr,
	guideSaveToOneStr,

	//adjust
	adjustStr,

	//work time
	currentTimeStr,
	lastTimeStr,

	//image quality
	imageQualityStr,
	
	//zoom and crop
	zoomStr,	
	zoomNewVUpStr,
	zoomNewVDownStr,
	zoomNewVUpAndDownStr,
	zoomNewHLeftStr,
	zoomNewHRightStr,
	zoomNewHLeftAndRightStr,
	zoomNewCenterStr,

	//vgamode
	vga1KeyModeStr,
	vga2KeyModeStr,
	vgaStr,
	ycbcrStr,

	FadeTimeStr,		//淡入淡出时间
	luminanceStr,

	hPolarityStr,
	vPolarityStr,
	positiveStr,
	negativeStr,

	ImageEnhanceStr,  //added by cyj
	
	bitDepthStr,
	bit_8Str,
	bit_10Str,
	bit_12Str,
	
	bootloaderstr,
  	bootCopyCodestr,
	bootRestartstr,

	ttlInterlaveModeStr,

	waitCallDelayStr,
	
	usbUpgradeWarnTipStr1,
	usbUpgradeWarnTipStr2,
		
	hotBackUpStr,  
	hotBackUpClass1Str,
	hotBackUpClass2Str,
	hotBackUpClass3Str,
	hotBackUpClass4Str,
	hotBackUpClass5Str,
	invalidFunctionInPIPStr,
	
	recordFreeStr,
	HdmiAdjustStr,	

	changeNotTakeEffectStr,
	untilRestartStr,

	// Version 
	softVersionStr,
	hardVersionStr,
	snStr,
	WriteSnStr,
	versionStr,
	mcuVersionStr,
	videoVersionStr,	
	commBoardVersionStr,
	mainBoaedVersionStr,
	fpgaVersionStr,
	extMainBoardVersionStr,
	ext2MainBoardVersionStr,
	ext1MainBoardSoftVersionStr,
	ext2MainBoardSoftVersionStr,
	wifiControl_VersionStr,

	edidManageStr,
	sourcePortStr,
	destinationPortStr,

	usbconnectStr,
	usbPortAStr,
	usbPortBStr,
	usbPhotoTimeStr,
	noUSBBoardStr,
	contactSalesStr,

	//edid	
	studyEDIDSuccessStr,
	studyEDIDFailStr,
	edidEditingStr,

	pleaseDoNotShautDownStr,
	pleaseWaitAutoRebootStr,

	//fan control
	fanControlStr,
	automaticSpeedControlStr,
	fanSpeedStr,
	CurTempStr,
	temperatureStr,

	//device status
	deviceStatusStr,
	videoProcessStatusStr,
	mbProcessStatusStr,
	extProcessStatusStr,
	unnormalStr,
	normalStr,

	invalidOperation2Str,
	inSplitModeStr,

	//black key type
	userDefinedButtonStr,
	mapKeyStr,
	blackZeroStr,
	blackDisplayModeStr,
	freezeDisplayModeStr,
	logoNaModeStr,
	tpDisplayModeStr,
	brightnessDisplayModeStr,

	noExternedModuleStr,
	noCVBoardStr,
	
	extCVBSControlStr,
	extCVBSPortStr,
	extCVBSPortAStr,
	extCVBSPortBStr,

	inputFormatStr,
	noInputStr,

	extVGAAdjustStr,

	saveRealTimeStr,
	
	fixedSplitStr,
	normalSplitStr,
	splitTypeStr,
    Horizontal2Str,
    Horizontal3Str,
	vertical2Str,
	//pipModeStr,
	fieldSplitStr,
	Horizontal4Str,
    vertical4Str,
    splitIndexStr,
	HorizontalNumberStr,
	VerticalNumberStr,

	//pad lock
	deviceInSerialControlStr,
	deviceInRemoteControlStr,	
	lockFrontPanelStr,

	readFilesFromUSBStr,
	readFilesFromUSBStr2,

	PreviewDblTapSwitchStr,
	PreviewSwitchStr,
	PreviewDVISwitchStr,	

	switchTypeStr,
	simpleVideoStr,
	complexVideoStr,

	englishLongStr,
	
	invalidOpInPIPModeStr,
	invalidOpInSPLITModeStr,
	SplitInvalidInPIPModeStr,

	collectingSignalStr,
	acquisitionCompleteStr,

	extInputConfigStr,

	dviAndAudioStr,
    audioTypeStr,

	noExtBoardTipStr,
	audioBoardTipStr,

	operationReadyTipStr,
	operationReadyFinishedTipStr,

	scalePauseStr,
	takeStr,
	noSignalNeedTakeStr,
	
	splitSourceLimitTipStr1,
	splitSourceLimitTipStr2,
	splitSourceLimitTipStr3,

	inTransitionStr,
	transitionFinishedStr,

	inputSDExhanceStr,

	noThisModuleStr,
	upgradeSkipStr,
	dvi1OutputStr,
	outputNormalStr,
	outputLoopStr,
	dvi1InputStr,

	hdmiAndExtAudioStr,
	mainBoardNotSupportStr,

	screenFollowStr,

	readUSBPlayListStr,

	audioInputConfigStr,
	audioInput1Str,
	audioInput2Str,
	audioInput3Str,
	
	noExtTipStr,
	throughModuleStr,
	hdmiAndExtAdjustStr,

	pressKeyStr,
	knobKeyStr,
	keyTestOnStr,

	advanceStr,

    portTutorialStr,
    sendCardSetWidthStr,
    sendCardAutoStr,
    sendCardManualStr,
    autoWidthParamStr,
    autoHeightParamStr,    
    wallSizeStr,
    panelPixelStr,
    wallSizeStr1,
    panelPixelStr1,   
    totalPixelStr,

	sendCardConfigStr,
	sendCardNormalStr,
	sendCardAbNormalStr,
	sendCardPortSetStr,
	sendCardCommonSetStr,
	sendCardPortSelStr,	
	sendCardHPanelsStr,	
	sendCardVPanelsStr,	
	sendCardHLedsStr,	
	sendCardVLedsStr,
	sendCardPortHOffsetStr,	
	sendCardPortVOffsetStr,
	sendCardPortH1OffsetStr,	
	sendCardPortV1OffsetStr,
	sendCardPortH2OffsetStr,	
	sendCardPortV2OffsetStr,
	sendCardPortH3OffsetStr,	
	sendCardPortV3OffsetStr,
	sendCardPortH4OffsetStr,	
	sendCardPortV4OffsetStr,	
	sendCardPortPanelStr,
	sendCardPanelNoStr,
	sendCardSendToPortStr,
	sendCardSendToPortOkStr,
	sendCardSendToPortFailStr,	
	sendCardSendToPanelStr,	
	sendCardResetPortStr,
	sendCardPortConectTypeStr,
	
	LEDScreenManageStr,
	quickPointScreenStr,
	displayConnectionStr,
	seniorstr,
	sendcardtypeStr,
	cascadeStr,
	receivingCardSeparateSettingStr,
	sendCardType_Colorlight,
	sendCardType_Linsn,
	sendCardType_NovaStar,

	sendcardadjuststr,	
	brightness_sendcardstr,
	positionstr,
	gamma_sendcard_str,
	connectstr,
	valuesetstr,
	
	hPosStr1,
	vPosStr1,
	hSizeStr1,
	vSizeStr1,
	
	sendcardchoosestr,
	
	parameterstr,
	
	vlinestr,
	hlinestr,
	vsize_str,
	hsize_str,
	screenconnectstr,
	receivecardstr,
	choosecard12str,
	positon_str,
	receivecard_number_str,
	versionstr,
	sendcardinfostr,
	receivecardinfostr,
	savebrightnessstr,
	networkastr,
	networkbstr,
	networkchoosestr,
	
	sendtoreceivestr,
	savetosendercardstr,
	
	xoffsetstr,
	yoffsetstr,
	sendcardstr,
	sendcardtype,

	 /////发送卡设置7
	 sendingCardSetStr,
	 sendingCardModelStr,
	 senddingCardNoStr,
	 videoResouutionStr,
	 sendCardOfffsetxStr,
	 sendCardOfffsetyStr,
	 saveToSenderCardstr,
	// 接收卡置 10
	 recevingCardSetStr,
	 horizontalCardStr,
	 verticalCarStr,
	 widthStr,
	 HeightStr,
	 ConnengctionModeStr,
	 DToUOffxStr,
	 DToUOffYstr,
	 sendToProtStr,
	 saveToReceiverStr,
	 portAStr,
	 portBStr,
	 portDStr,
	 portUStr,
	 port1Str,
	 port2Str,
	 port3Str,
	 port4Str,

	card1Str,
	card2Str,

	naStr,

	readLEDInfoStr,
	pleaseWaitForOneMinuteStr,

	invalidInPIPOrSplitModeStr,
	
	hdmiColorSpaceAdjustStr,

//1#################################################################################################################	
//1显示屏连接菜单字符串定义	
	//gamma_sendcard_str,
	sendcardsetStr,
	recevingcardSetStr,
	ColorTempSetStr,


#if ENABLE_TEST_GRID_CONTROL
	GridTestStr,
	gridBackgroudStr,
	gridModeStr,
	gridColorStr,
	gridDotColorStr,	
	gridHSpaceStr,
	gridVSpaceStr,
	gridDotStr,
	gridDotMoveStr,
	gridDotStillStr,
	gridDotManualStr,
	gridDotHideStr,	
	gridDotSpeedStr,
	//gridDotColorRStr, 
	//gridDotColorGStr,
	//gridDotColorBStr, 
	//gridDotPosXStr,
	//gridDotPosYStr,
	lineModeCrossStr,
	lineModeHStr,
	lineModeVStr,
	lineModeBordersStr,	

#endif
	videoPanelFirmwareStr,
	sendStr,
	saveStr,
	fromUSBStr,
	fromInternalMemStr,

	artNetStartAddrStr,
	artNetUniverseStr,

	logoStr,
	customLogoStr,
	customStr,

	celsiusStr,
	fahrenheitStr,
	
	//###############################################################################################################################
	//检查发送卡
	CheckSendCard,
	NoSendCard,
	CardTypeLinsn,
	CardTypeColorlight,
	CardTypeNowa,


	mainWinWidth,
	mainWinHeigh,
	subWinWidth,
	subWinHeigh,
	
	totalWidth,
	totalHeigh,
	firstDisWidth,
	firstDisHeigh,
	secondDisWidth,
	secondDisHeigh,
	thirdDisWidth,
	thirdDisHeigh,
	fourthDisWidth,
	fourthDisHeigh,

	//############################################################################################################
	//输出分辨率
	output800x600_60Str,
	output1024x768_60Str,
	output1280x720_60Str,
	output1280x720_50Str,
	output1280x768_60Str,
	output1280x800_60Str,
	output1280x1024_60Str,
	output1360x768_60Str,
	output1366x768_60Str,
	output1400x1050_60Str,
	output1440x900_60Str,
	output1600x1200_60Str,
	output1680x1050_60Str,
	output1920x1080_60Str,
	output1920x1080_50Str,
	output1920x1200_60Str,
	output2048x1152_60Str,
	output2560x812_60Str,
	//output2560x816_60Str,
	//output3840x1080_60Str,
	//output3840x2160_30Str,
	outputCustomStr,

	
	//############################################################################################################
	//EDID
	hdmi20PortStr,
	hdmi14PortStr,
	dpPortStr,
	dviPortStr,
	hdmi20EdidStr,
	hdmi20VideoEdidStr,
	hdmi20NoHfvsdbNo420, 	
	hdmi20NoHfvsdbWith420, 	
	hdmi20WithHfvsdbNo420, 	
	hdmi20WithHfvsdbNo420Hdr,
	hdmi20WithHfvsdbWith420,
	hdmi14EdidStr,
	hdmi13EdidStr,
	dviEdidStr,
	dualLinkDviEdidStr,
	dpEdidStr,
	dp4k2k60EdidStr,
	dp4k2k30EdidStr,
	//dpEdidStr,
	customerEdidStr,
	diaplayAlphaStr,
	pgmInputSourceStr,
	prvInputSourceStr,
	pipMainInputSrt,
	pipSubInputSrt,
	pipSubPosXSrt,
	pipSubPosYSrt,
	pipSubSizeXSrt,
	pipSubSizeYSrt,
	
	outputPortSelSrt,
	outputPort0Srt,
	outputPort1Srt,
	outputPort2Srt,
	outputPort3Srt,

	outputTpyeStr,
	bitWidthSrt,
	rangeStr,

	layerParamSrt,
	layerAHSizeSrt,
	layerAVSizeSrt,
	layerAHPosSrt,
	layerAVPosSrt,
	layerASplitStartSrt,
	layerACropStartSrt,

	//layerParamSrt,
	layerBHSizeSrt,
	layerBVSizeSrt,
	layerBHPosSrt,
	layerBVPosSrt,
	layerBSplitStartSrt,
	layerBCropStartSrt,

	//layerParamSrt,
	layerCHSizeSrt,
	layerCVSizeSrt,
	layerCHPosSrt,
	layerCVPosSrt,
	layerCSplitStartSrt,
	layerCCropStartSrt,

	//layerParamSrt,
	layerDHSizeSrt,
	layerDVSizeSrt,
	layerDHPosSrt,
	layerDVPosSrt,
	layerDSplitStartSrt,
	layerDCropStartSrt,

	FineSrt,

	outPutDvi1srt,
	outPutDvi2srt,
	outPutDvi3srt,
	outPutDvi4srt,

	maxStrSize,
} Lang_StrIndex_Typedef;

void lang_SetLang(Lang_TypeDef lang);
Lang_TypeDef lang_GetLang(void);
char * lang_GetEnStrByIndex(int index);
char * lang_GetCnStrByIndex(int index);
char * langGetStr(int index);



#endif



